//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graders.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRole
    {
        public CustomerRole()
        {
            this.Customer = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
    }
}
