//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graders.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GradersEntities : DbContext
    {
        public GradersEntities()
            : base("name=GradersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerRole> CustomerRole { get; set; }
        public virtual DbSet<InsCourseLocationMapping> InsCourseLocationMapping { get; set; }
        public virtual DbSet<Institute> Institute { get; set; }
        public virtual DbSet<InstituteReview> InstituteReview { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<MultipleLocation> MultipleLocation { get; set; }
        public virtual DbSet<Ratings> Ratings { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
    }
}
