//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graders.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsCourseLocationMapping
    {
        public int Id { get; set; }
        public Nullable<int> InstituteId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Institute Institute { get; set; }
        public virtual Location Location { get; set; }
    }
}
