//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graders.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institute
    {
        public Institute()
        {
            this.InsCourseLocationMapping = new HashSet<InsCourseLocationMapping>();
            this.InstituteReview = new HashSet<InstituteReview>();
            this.MultipleLocation = new HashSet<MultipleLocation>();
        }
    
        public int InstituteId { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<InsCourseLocationMapping> InsCourseLocationMapping { get; set; }
        public virtual ICollection<InstituteReview> InstituteReview { get; set; }
        public virtual ICollection<MultipleLocation> MultipleLocation { get; set; }
    }
}
