//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graders.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstituteReview
    {
        public int ReviewId { get; set; }
        public Nullable<int> InstituteId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Review { get; set; }
        public Nullable<int> Rating { get; set; }
        public System.DateTime DateOfReview { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Institute Institute { get; set; }
        public virtual Ratings Ratings { get; set; }
    }
}
