//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graders.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultipleLocation
    {
        public int MLocationId { get; set; }
        public Nullable<int> InstituteId { get; set; }
        public string FullAddress { get; set; }
        public int PhoneNo { get; set; }
        public string Website { get; set; }
    
        public virtual Institute Institute { get; set; }
    }
}
