//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graders.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ratings
    {
        public Ratings()
        {
            this.InstituteReview = new HashSet<InstituteReview>();
        }
    
        public int RatingId { get; set; }
        public string RatingName { get; set; }
    
        public virtual ICollection<InstituteReview> InstituteReview { get; set; }
    }
}
